config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :posts
  get "/search" => "posts#search", as: :search_post

  resource  :session
  get "/:id" => "users#show", as: :user

  resources :stocks, only: %i(create destroy)
  get "/:id/stocks" => "stocks#index", as: :index_stock

  resources :comments, only: %i(create update destroy)

  get '/auth/google_oauth2/callback' => 'sessions#create_by_omniauth'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :stocks, dependent: :destroy
  has_many :stocked_users, through: :stocks, class_name: 'User', source: :user
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :stocks, dependent: :destroy
  has_many :stocked_posts, through: :stocks, class_name: 'Post', source: :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authorization

  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @currnet_user ||= User.find_by(id: session[:user_id])
  end

  def destroy_current_user
    @currnet_user = nil
    session[:user_id] = nil
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    Comment.create!(comment_params)
    redirect_to :back
  end

  def update
  end

  def destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:post_id, :body).merge(user: current_user)
  end
end

app/controllers/concerns/authorization.rb
module Authorization
  extend ActiveSupport::Concern

  def authorization_required
    redirect_to '/auth/google_oauth2' unless current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorization_required, except: %i(index show)

  def show
    @post     = Post.find_by(id: params[:id]).decorate
    @stock    = Stock.find_by(user_id: current_user, post_id: @post)
    @comments = @post.comments
    @comment  = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.create!(post_params)
    redirect_to post_url(post)
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def search
  end

  private

  def post_params
    params.require(:post).permit(:title, :body).merge(user: current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create_by_omniauth
    env = request.env['omniauth.auth']
    user = User.find_or_initialize_by(uid: env[:uid])
    user.update!(
      uid:        env[:uid],
      name:       env[:info][:name],
      first_name: env[:info][:first_name],
      last_name:  env[:info][:last_name],
      email:      env[:info][:email],
      nickname:   env[:info][:email].split('@').first,
      image_url:  env[:info][:image]
    )
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    destroy_current_user
    redirect_to root_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
    @posts = User.find_by(nickname: params[:id]).stocked_posts
  end

  def create
    @stock = Stock.find_or_create_by(user_id: current_user.id, post_id: params[:post_id])
  end

  def destroy
    stock = Stock.find_by(id: params[:id])
    @post = stock.post
    stock.destroy if stock.user == current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(nickname: params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.includes(:user).order("created_at DESC").limit(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      = link_to 'Aiita', root_path, class: 'navbar-brand'
    #navbar.navbar-collapse.collapse
      %form.navbar-form.navbar-left{role: "search", action: "/search"}
        .form-group
          %input.form-control{placeholder: "キーワードを入力", type: "text"}/
        %button.btn.btn-default{type: "submit"} 検索
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to '新規投稿', new_post_path
        - if current_user
          %li
            = link_to 'ストック一覧', index_stock_path(current_user.nickname)
        - unless current_user
          %li
            = link_to 'ログイン', '/auth/google_oauth2'
        - else
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", href: "#", role: "button"}
              = current_user.nickname
              %span.caret
            %ul.dropdown-menu{"aria-labelledby" => "drop3", role: "menu"}
              %li{role: "presentation"}
                = link_to 'マイページ', user_path(current_user.nickname), role: 'menuitem', tabindex: '-1'
              %li.divider{role: "presentation"}
              %li{role: "presentation"}
                = link_to 'ログアウト', session_path, method: :delete, role: 'menuitem', tabindex: '-1'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Aiita
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/nav'

    .container
      = yield

app/views/posts/edit.html.haml
%h1 Posts#edit
%p Find me in app/views/posts/edit.html.haml

app/views/posts/new.html.haml
= form_for(@post) do |post|
  .row
    .col-md-6
      .form-group
        = post.text_field :title, class: 'form-control', placeholder: "タイトル"
      .form-group
        = post.text_area :body, class: 'form-control', rows: "19", placeholder: "Markdown"
      = post.submit "投稿する", class: "btn btn-primary btn-lg btn-block"

    .col-md-6
      .jumbotron{style: "font-size: 24px;height:500px;"}
        Preview Area

app/views/posts/search.html.haml
%h1 検索結果

まだ実装されていません。Feel free to send a Pull Request.

app/views/posts/show.html.haml
#stock
  - unless @stock
    = render partial: "stocks/create", locals: { post: @post }
  - else
    = render partial: "stocks/destroy", locals: { stock: @stock }

%h1= @post.title

= @post.to_html

%h2 コメント

- if @comments.any?
  - @comments.each do |comment|
    %p= comment.user.nickname
    %p= comment.body

= form_for(@comment) do |f|
  = f.hidden_field :post_id, value: @post.id
  %p= f.text_area :body
  %p= f.submit "コメントする"

app/views/stocks/_create.html.haml
= link_to 'ストックする', stocks_path(post_id: post), method: :post, remote: true

app/views/stocks/_destroy.html.haml
= link_to 'ストックを解除する', stock_path(@stock), method: :delete, remote: true

app/views/stocks/create.js.erb
$('#stock').html(
  "<%= escape_javascript(render(partial: "stocks/destroy", locals: { stock: @stock })) %>"
);

app/views/stocks/destroy.js.erb
$('#stock').html(
  "<%= escape_javascript(render(partial: "stocks/create", locals: { post: @post })) %>"
);

app/views/stocks/index.html.haml
%h1 ストック一覧

- @posts.each do |post|
  %p= post.title

app/views/users/show.html.haml
%h1 Users#show

= @user.name

app/views/welcome/index.html.haml
.row
  %article.col-md-12
    %h2 最新の投稿

    %table.table
      - @posts.each do |post|
        %tr
          %td.feed-title= link_to post.title, post_path(post)
          %td
            %img{src: "#{post.user.image_url}", width: '36', height: '36'}
          %td= post.user.nickname
          %td= time_ago_in_words(post.created_at)